name:                adhoc-serve
version:             0.1.1.0
synopsis:            Serve files from a directory
description:         A command line program to quickly create an http server for serving files from one or more directories on a local disk.
homepage:            https://github.com/luntain/adhoc-serve#readme
license:             BSD3
author:              Kamil Dworakowski
maintainer:          kamil@dworakowski.name
copyright:           2020 Kamil Dworakowski
category:            Web
extra-source-files:
- README.md
- changelog.md

dependencies:
  - base >= 4.7 && < 5
  - text
  - snap-core
  - snap-server
  - random
  - uuid
  - bytestring
  - containers
  - optparse-applicative
  - hostname

executables:
  adhoc-serve:
    source-dirs:      src
    main:             Main.hs
